export default {
  mockEventData: {
    page_1: {
      "links": {
        "next": null,
        "previous": null
      },
      "total_count": 20,
      "total_pages": 3,
      "current_page": 1,
      "results": [
        {
          "author": 2,
          "id": 7,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 6,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 5,
          "name": "string",
          "place": "string",
          "amount_members": 130,
          "status": "Planned",
          "gender": "Man",
          "price": 1700,
          "type": "Bouling",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 6,
          "count_fans": 1
        },
        {
          "author": 2,
          "id": 4,
          "name": "string",
          "place": "string",
          "amount_members": 30,
          "status": "Planned",
          "gender": "Man",
          "price": 1000,
          "type": "Handball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 3,
          "count_fans": 5
        },
        {
          "author": 2,
          "id": 3,
          "name": "string",
          "place": "string",
          "amount_members": 40,
          "status": "Planned",
          "gender": "Man",
          "price": 1200,
          "type": "Football",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 1,
          "count_fans": 0
        },
        {
          "author": 2,
          "id": 2,
          "name": "string",
          "place": "string",
          "amount_members": 10,
          "status": "Planned",
          "gender": "Man",
          "price": 1200,
          "type": "Football",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-11-10T17:15:00+03:00",
          "count_current_users": 0,
          "count_fans": 0
        },
        {
          "author": 2,
          "id": 1,
          "name": "string",
          "place": "string",
          "amount_members": 10,
          "status": "Planned",
          "gender": "Man",
          "price": 1200,
          "type": "Football",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-11-10T17:15:00+03:00",
          "count_current_users": 0,
          "count_fans": 0
        }
      ]
    },
    page_2: {
      "links": {
        "next": null,
        "previous": null
      },
      "total_count": 20,
      "total_pages": 3,
      "current_page": 2,
      "results": [
        {
          "author": 2,
          "id": 14,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 13,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 12,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 11,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 10,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 9,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 8,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        }
      ]
    },
    page_3: {
      "links": {
        "next": null,
        "previous": null
      },
      "total_count": 20,
      "total_pages": 3,
      "current_page": 3,
      "results": [
        {
          "author": 2,
          "id": 20,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 19,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 18,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 17,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 16,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        },
        {
          "author": 2,
          "id": 15,
          "name": "string",
          "place": "string",
          "amount_members": 23,
          "status": "Planned",
          "gender": "Man",
          "price": 1900,
          "type": "Litrball",
          "need_ball": true,
          "need_form": true,
          "date_and_time": "2022-12-11T12:13:00+03:00",
          "count_current_users": 4,
          "count_fans": 8
        }
      ]
    }
  },
  biggerData: {
    "links": {
      "next": null,
      "previous": null
    },
    "total_count": 20,
    "total_pages": 3,
    "current_page": 2,
    "results": [
      {
        "author": 2,
        "id": 14,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 13,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 12,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 11,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 10,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 9,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 8,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 20,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 19,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 18,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 17,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 16,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      },
      {
        "author": 2,
        "id": 15,
        "name": "string",
        "place": "string",
        "amount_members": 23,
        "status": "Planned",
        "gender": "Man",
        "price": 1900,
        "type": "Litrball",
        "need_ball": true,
        "need_form": true,
        "date_and_time": "2022-12-11T12:13:00+03:00",
        "count_current_users": 4,
        "count_fans": 8
      }
    ]
  }
}