name: Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_PATH: ./deploy/Dockerfile
      LATEST_IMAGE: ${{ secrets.DOCKER_REGISTRY }}:latest
      COMMIT_IMAGE: ${{ secrets.DOCKER_REGISTRY }}:${{ github.sha }}
    steps:
    - uses: actions/checkout@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull latest image
      run: |
        docker pull ${LATEST_IMAGE}

    - name: Build image
      working-directory: .
      run: |
        docker build -f ${DOCKERFILE_PATH} --cache-from ${LATEST_IMAGE} -t ${COMMIT_IMAGE} .

    - name: Tag latest image
      run: |
        docker tag ${COMMIT_IMAGE} ${LATEST_IMAGE}

    - name: Push images
      run: |
        docker push ${COMMIT_IMAGE}
        docker push ${LATEST_IMAGE}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deploy in portainer
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
